import { FormValues } from "@/interface/interfaceValues";

export const initialValues: FormValues = {
    porfilespic: "",
    age: "",
    gender: "",
    religion: "",
    race: "",
    resumepic: "",
    yearsofexperience: "",
    favouritequote: "",
    hobbies: [],
    country: "",
    state: "",
    address: "",
    institutename: "",
    degree:"",
    fieldofstudy:"",
    startdate:"",
    enddate:"",
    certificate:"",
    companyname:"",
    jobtitle:"",
    j_startdate:"",
    j_enddate:"",
    jobdescription:"",
    experiencecertificate:"",
    specialization:[],
    l_state:"",
    npi_number:"",
    liscense:"",
    insurance:"",
    t_startdate:"",
    t_enddate:"",
    select_bank:"",
    acc_title:"",
    ibanNumber:""
  };